functionality:
  name: star_create_reference
  namespace: mapping
  description: Create a reference for STAR from a set of fasta files.
  authors:
    - __merge__: ../../authors/dries_schaumont.yaml
      roles: [ author ]
  argument_groups:
    - name: Input/Output
      arguments:
        - type: file
          name: --input
          required: true
          description: The fasta files to be included in the reference.
          example: [ chr1.fasta, chr2.fasta ]
          multiple: true
          multiple_sep: " "
        - name: --output
          type: file
          description: Path to output directory.
          example: /path/to/foo
          direction: output
          required: true
        - name: --sjdbGTFfile
          type: file
          direction: input
          description: | 
            Specifes the path to the file with annotated transcripts in the standard GTF
            format. STAR will extract splice junctions from this file and use them to greatly improve
            accuracy of the mapping.
          required: false
    - name: "extra options"
      arguments:
      - type: integer
        name: --genomeSAindexNbases
        description: |
          Length (bases) of the SA pre-indexing string. Typically between 10 and 15.
          Longer strings will use much more memory, but allow faster searches. For small
          genomes, the parameter {genomeSAindexNbases must be scaled down to
          min(14, log2(GenomeLength)/2 - 1).
        required: false
        default: 14
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
    - path: ../../../resources_test/cellranger_tiny_fastq
platforms:
  - type: docker
    image: ubuntu:latest
    setup:
      # setup derived from https://github.com/alexdobin/STAR/blob/master/extras/docker/Dockerfile
      - type: docker
        env: 
          - STAR_VERSION 2.7.10a
          - PACKAGES gcc g++ make wget zlib1g-dev unzip
      - type: docker
        run: |
          apt-get update && \
            apt-get install -y --no-install-recommends ${PACKAGES} && \
            apt-get clean && \
            g++ --version && \
            cd /home && \
            wget --no-check-certificate https://github.com/alexdobin/STAR/archive/${STAR_VERSION}.zip && \
            unzip ${STAR_VERSION}.zip && \
            cd STAR-${STAR_VERSION}/source && \
            make STARstatic CXXFLAGS_SIMD=-std=c++11 && \
            mkdir /home/bin && \
            cp STAR /home/bin && \
            cd /home && \
            'rm' -rf STAR-${STAR_VERSION} && \
            apt-get --purge autoremove -y  ${PACKAGES}
      - type: docker
        env: 
          - PATH /home/bin:${PATH}
  - type: nextflow
    directives:
      label: [ highmem, highcpu ]