functionality:
  name: convert_10x_h5_to_h5ad
  namespace: "convert"
  version: "dev"
  description: |
    Converts an h5 into an h5ad file.
  authors:
    - name: Dries De Maeyer
      email: ddemaeyer@gmail.com
      roles: [ maintainer ]
      props: { account: ddemaey1 }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5 file
      default: input.h5
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5ad file.
      default: output.h5ad
      direction: output
    - name: "--compression"
      type: string
      description: The compression format to be used on the final h5ad object.
      default: "gzip"
    - name: "--modality"
      type: string
      default: "Gene Expression"
      description: The feature type to extract to the h5ad file.
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: run_test.py
    - path: ../../../resources/test/pbmc_1k_protein_v3_filtered_feature_bc_matrix.h5
platforms:
  - type: docker
    image: python:3.8
    python:
      packages:
        - anndata
        - loompy
  - type: nextflow
