functionality:
  name: lognorm
  namespace: "normalize"
  version: "dev"
  description: |
    Performs a log normalization on a h5ad file.
  authors:
    - name: Dries De Maeyer
      email: ddemaeyer@gmail.com
      roles: [ maintainer ]
      props: { account: ddemaey1 }
  arguments:
    - name: "--input"
      type: file
      description: Input h5ad file
      direction: input
      required: true
      example: input.h5mu
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5ad file.
      direction: output
      required: true
      example: output.h5mu
    - name: "--modality"
      type: string
      multiple: true
      default: "rna"
      required: false
    - name: "--normalized_umi_count"
      type: integer
      default: 10000
      required: false
    - name: "--regress_out_variables"
      type: string
      multiple: true
      required: false
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: bash_script
      path: test.sh
    - path: ../../../resources/test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: python:3.8
    setup:
      - type: python
        packages:
          - scanpy
          - muon
  - type: nextflow
