functionality:
  name: "cellranger"
  namespace: "ingestion"
  description: "Cell Ranger ingestion pipeline (demux and mapping)."
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      required: true
      type: file
      description: A BCL directory.
      example: /path/to/bcl
    - name: "--sample_sheet"
      required: true
      type: file
      description: The sample sheet for the samples to be demultiplexed.
      example: sample_sheet.csv
    - name: "--reference"
      required: true
      type: file
      description: Path to a Cell Ranger reference.
      example: reference.tar.gz
  resources:
    - type: nextflow_script
      path: main.nf
    - path: nextflow.config
  # test_resources:
  #   - type: nextflow_script
  #     path: main.nf
  #     entrypoint: test_wf
platforms:
  - type: native