name: viash release CI

on:
  push:
    tags: [ * ]

jobs:
  viash-release:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: true
      matrix:
        config:
        - {name: 'main', os: ubuntu-latest }

    steps:
    - uses: actions/checkout@v2

    - name: Run build
      run: |
        bin/viash_build -r openpipeline -m release -t 0.1.0

    - name: Run tests
      run: |
        # create check_results folder
        sed -i '/^build_results\/$/d' .gitignore
        mkdir build_results

        # run tests
        bin/viash_test -r openpipeline -m release -t 0.1.0 --append=false --log=build_results/results.tsv

    - name: Push containers
      run: |
        bin/viash_push -r openpipeline -m release -t 0.1.0

    - name: Deploy to target branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: main_build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: *

    - name: Upload check results
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: build_results

